#修改TNAME: K2P 中的K2P为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan K2 PSG1218a

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      env:
        KERNEL: 3.4
      run: |
        if [ $KERNEL = "4.4" ] ; then
        git clone --depth=1 https://github.com/goodwinY/padavan-4.4.git /opt/rt-n56u
        else
        git clone --depth=1 https://github.com/goodwinY/rt-n56u.git /opt/rt-n56u
        fi
    - name: Build Firmware
      env:
        TNAME: PSG1218_nano
        KERNEL: 3.4
      run: |
        if [ ! -f $TNAME.config ] ; then
        echo "$TNAME.config not found "
        exit 1
        fi
        cp -f $TNAME.config /opt/rt-n56u/trunk/.config
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/        
        cd /opt/rt-n56u/trunk        
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
